import React from 'react'
import { CNavItem, CNavTitle } from '@coreui/react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {
  faTachometerAlt,
  faBox,
  faFileText,
  faFileInvoiceDollar,
  faTruck,
  faUsers,
  faClipboardList,
  faChartBar,
  faBullhorn,
  faReceipt,
  faShippingFast,
  faComments,
  faTruckLoading,
  faBoxes,
  faCog,
  faUserCog,
} from '@fortawesome/free-solid-svg-icons'

const _nav = [
  {
    component: CNavItem,
    name: 'Dashboard',
    to: '/dashboard',
    icon: <FontAwesomeIcon icon={faTachometerAlt} className="nav-icon" />,
  },
  {
    component: CNavTitle,
    name: 'ACCESSIBLE BY ADMINS',
    role_exclude: ['vendor', 'user', 'staff'],
  },
  {
    component: CNavItem,
    name: 'Approval',
    to: '/admin/approval',
    role_exclude: ['vendor', 'user', 'staff'],
    icon: <FontAwesomeIcon icon={faFileText} className="nav-icon" />,
  },
  {
    component: CNavItem,
    name: 'Vendor Management',
    to: '/procurement/vendors',
    role_exclude: ['vendor', 'user', 'staff'],
    icon: <FontAwesomeIcon icon={faUsers} className="nav-icon" />,
  },
  {
    component: CNavItem,
    name: 'Award Management',
    to: '/award',
    role_exclude: ['vendor', 'user', 'staff'],
    icon: <FontAwesomeIcon icon={faBullhorn} className="nav-icon" />,
  },
  {
    component: CNavTitle,
    name: 'Procurement',
    role_exclude: ['vendor', 'user', 'staff'],
  },
  {
    component: CNavItem,
    name: 'Procurement request',
    to: '/procurement/procurement',
    role_exclude: ['vendor', 'staff'],
    icon: <FontAwesomeIcon icon={faBox} className="nav-icon" />,
  },
  {
    component: CNavItem,
    name: 'PR & RFQ List',
    to: '/procurement/rfq-management',
    role_exclude: ['vendor', 'staff'],
    icon: <FontAwesomeIcon icon={faFileText} className="nav-icon" />,
  },
  {
    component: CNavItem,
    name: 'Vendor Quotes',
    to: '/procurement/submit-quote',
    role_exclude: ['vendor', 'staff'],
    icon: <FontAwesomeIcon icon={faBox} className="nav-icon" />,
  },
  {
    component: CNavItem,
    name: 'Purchase Order & Payment Tracking',
    to: '/procurement/po-payments',
    role_exclude: ['vendor', 'user', 'staff'],
    icon: <FontAwesomeIcon icon={faFileInvoiceDollar} className="nav-icon" />,
  },
  {
    component: CNavItem,
    name: 'Shipment & Delivery Tracking',
    to: '/procurement/shipments',
    role_exclude: ['vendor', 'user', 'staff'],
    icon: <FontAwesomeIcon icon={faTruck} className="nav-icon" />,
  },
  {
    component: CNavItem,
    name: 'Product Catalog',
    to: '/procurement/product-catalog',
    role_exclude: ['vendor', 'user', 'staff'],
    icon: <FontAwesomeIcon icon={faClipboardList} className="nav-icon" />,
  },
  {
    component: CNavItem,
    name: 'Reports & Dashboard',
    to: '/procurement/analytics',
    role_exclude: ['vendor', 'user', 'staff'],
    icon: <FontAwesomeIcon icon={faChartBar} className="nav-icon" />,
  },
  {
    component: CNavTitle,
    name: 'VENDOR MANAGEMENT',
    role_exclude: ['user', 'staff'],
  },
  {
    component: CNavItem,
    name: 'RFQ Announcements & Bidding',
    to: '/vendor/rfqs',
    role_exclude: ['user', 'staff'],
    icon: <FontAwesomeIcon icon={faBullhorn} className="nav-icon" />,
  },
  {
    component: CNavItem,
    name: 'Quotes Requests',
    to: '/vendor/quotes',
    role_exclude: ['user', 'staff'],
    icon: <FontAwesomeIcon icon={faBullhorn} className="nav-icon" />,
  },
  {
    component: CNavItem,
    name: 'Order & Payment',
    to: '/vendor/order-payment',
    role_exclude: ['user', 'staff'],
    icon: <FontAwesomeIcon icon={faReceipt} className="nav-icon" />,
  },
  {
    component: CNavItem,
    name: 'Shipment & Delivery',
    to: '/vendor/shipments',
    role_exclude: ['user', 'staff'],
    icon: <FontAwesomeIcon icon={faShippingFast} className="nav-icon" />,
  },
  {
    component: CNavItem,
    name: 'Communication Support',
    to: '/vendor/communication',
    role_exclude: ['user', 'staff'],
    icon: <FontAwesomeIcon icon={faComments} className="nav-icon" />,
  },
  {
    component: CNavTitle,
    name: 'LOGISTICS',
    role_exclude: ['vendor', 'user', 'staff'],
  },
  {
    component: CNavItem,
    name: 'Logistics Dashboard',
    to: '/logistics/dashboard',
    role_exclude: ['vendor', 'user', 'staff'],
    icon: <FontAwesomeIcon icon={faTruckLoading} className="nav-icon" />,
  },
  {
    component: CNavTitle,
    name: 'INVENTORY MANAGEMENT',
    role_exclude: ['vendor', 'user', 'staff'],
  },
  {
    component: CNavItem,
    name: 'Inventory',
    to: '/inventory',
    role_exclude: ['vendor', 'user', 'staff'],
    icon: <FontAwesomeIcon icon={faBoxes} className="nav-icon" />,
  },
  {
    component: CNavTitle,
    name: 'ANALYTICS',
    role_exclude: ['vendor', 'user', 'staff'],
  },
  {
    component: CNavItem,
    name: 'Settings',
    to: '/settings',
    role_exclude: ['vendor', 'user', 'staff'],
    icon: <FontAwesomeIcon icon={faCog} className="nav-icon" />,
  },
  {
    component: CNavItem,
    name: 'General Settings',
    to: '/settings/general',
    role_exclude: ['vendor', 'user', 'staff'],
    icon: <FontAwesomeIcon icon={faCog} className="nav-icon" />,
  },
  {
    component: CNavItem,
    name: 'User Management',
    to: '/settings/user-management',
    role_exclude: ['vendor', 'user', 'staff'],
    icon: <FontAwesomeIcon icon={faUserCog} className="nav-icon" />,
  },
]

export default _nav
